# Generated by Django 6.0.6 on 2026-07-14 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_alter_dailyfatiguereport_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remedy",
            name="days_of_week",
        ),
    ]
